package example.micronaut

import io.micronaut.context.ApplicationContext
import io.micronaut.core.type.Argument
import io.micronaut.http.HttpRequest
import io.micronaut.http.HttpStatus
import io.micronaut.http.client.RxStreamingHttpClient
import io.micronaut.runtime.server.EmbeddedServer
import io.reactivex.Flowable
import org.spekframework.spek2.Spek
import org.spekframework.spek2.style.specification.describe
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

class BintrayControllerSpec: Spek({
    val expectedProfileNames = arrayOf("base", "federation", "function", "function-aws", "service")
    describe("BintrayController") {

        var embeddedServer : EmbeddedServer = ApplicationContext.run(EmbeddedServer::class.java) // <1>
        var client : RxStreamingHttpClient = RxStreamingHttpClient.create(embeddedServer.url) // <2>
        it("Verify bintray packages can be fetched with low level HttpClient") {
            val request = HttpRequest.GET<Any>("/bintray/packages-lowlevel")
            val rsp = client.toBlocking().exchange(request,   // <3>
                    Argument.of(List::class.java, BintrayPackage::class.java))  // <4>

            assertEquals(rsp.status()!!, HttpStatus.OK) // <5>
            assertNotNull(rsp.body()) // <6>

            for (name in expectedProfileNames) {
                var found = false
                for ( bintraypackage in rsp.body() as List<BintrayPackage>) {
                    found = name == bintraypackage.name
                    if(found) {
                        break
                    }
                }
                assertTrue(found)
            }
        }
        it("Verify bintray packages can be fetched with compile-time autogenerated @Client") {
            val request = HttpRequest.GET<Any>("/bintray/packages")
            val bintrayPackageStream : Flowable<BintrayPackage> = client.jsonStream(request, BintrayPackage::class.java)  // <7>
            val bintrayPackages : Iterable<BintrayPackage> = bintrayPackageStream.blockingIterable()

            for (name in expectedProfileNames) {
                var found = false
                for ( bintraypackage in bintrayPackages) {
                    found = name == bintraypackage.name
                    if(found) {
                        break
                    }
                }
                assertTrue(found)
            }
        }

        afterGroup {
            client.close()
            embeddedServer.close()
        }

    }
})
